dsc: fix compilation error because of symbol clashes
src/dsc.c:34:17: Fehler: In Konflikt stehende Typen für »clock«
/usr/include/time.h:183:16: Anmerkung: Vorherige Deklaration von »clock« war hier

Signed-off-by: Patrick McHardy <kaber@trash.net>